name: Man10Commerce
version: 1.0
main: red.man10.man10commerce.Man10Commerce
depend:
  - Man10Bank
  - Vault
softdepend:
  - Man10CommonLibs
api-version: 1.21
commands:
  amzn:
    default: op
  amsell:
    default: op
  amsellop:
    default: op
  amsearch:
    default: op
  amauthor:
    default: op